version: 2

updates:
  - commit-message:
      prefix: ci(deps)"
    directory: /
    package-ecosystem: github-actions
    schedule:
      interval: monthly
    groups:
      actions-deps:
        patterns:
          - '*'
