# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#using_default_substitutions
steps:
  - name: gcr.io/cloud-builders/docker
    args: [ 'build',
          '-t', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/binary-store/${REPO_NAME}-image:${SHORT_SHA}',
          '-t', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/binary-store/${REPO_NAME}-image:latest',
          '.'
    ]
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/binary-store/${REPO_NAME}-image:${SHORT_SHA}']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ejks-sk
      - '--image'
      - europe-west1-docker.pkg.dev/${PROJECT_ID}/binary-store/${REPO_NAME}-image:${SHORT_SHA}
      - '--region'
      - europe-west1
images:
  - europe-west1-docker.pkg.dev/${PROJECT_ID}/binary-store/${REPO_NAME}-image:${SHORT_SHA}
  - europe-west1-docker.pkg.dev/${PROJECT_ID}/binary-store/${REPO_NAME}-image:latest
