name: Deploy to GitHub Pages

on:
  push:
    branches:
      # - master
      - legacy
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    shell: sh

jobs:
  deploy:
    container: php:8.4.1-cli-alpine3.19
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build content
        run: |
          ./_legacy/build.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
